"""Build the profile README as a single composite "poster" SVG per theme (dark + light) plus README.md.

Why a poster: the README is uploaded through the GitHub web UI, so it must be a handful of files, not
hundreds of separate icons. Everything (header, key figures, the whole tech grid, footer) is composed into
one self-contained SVG per theme. README.md shows the poster via <picture> so GitHub picks dark or light,
plus a short intro with real markdown links.

Usage:  python tools/poster.py
"""
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
sys.path.insert(0, str(HERE))

import build_assets as B          # noqa: E402  (glyph_svg, legible, icon_tile, esc)
import components as C            # noqa: E402  (header, metrics, category_label, THEME, text_width, f)

PROFILE = json.loads((HERE / "profile.json").read_text(encoding="utf-8"))
TECH = json.loads((HERE / "tech.json").read_text(encoding="utf-8"))
GLYPHS = json.loads((HERE / "glyphs.json").read_text(encoding="utf-8"))

W = 1200
PAD = 40
TILE = 66
GAP = 14


def strip_svg(svg):
    """Return the inner markup of a 96x96 tile SVG (drop the outer <svg ...> wrapper)."""
    i = svg.index(">") + 1
    j = svg.rindex("</svg>")
    return svg[i:j]


def tile(key, g, theme, x, y):
    inner = strip_svg(B.icon_tile(key, g, theme))
    return f'<svg x="{x}" y="{y}" width="{TILE}" height="{TILE}" viewBox="0 0 96 96">{inner}</svg>'


def wrap(text, size, weight, max_w):
    lines, cur = [], ""
    for word in text.split():
        cand = f"{cur} {word}".strip()
        if cur and C.text_width(cand, size, weight) > max_w:
            lines.append(cur)
            cur = word
        else:
            cur = cand
    if cur:
        lines.append(cur)
    return lines


def poster(theme):
    t = C.THEME[theme]
    parts = []
    y = 0

    # 1) header (its own 1200x320 SVG, nested)
    head = strip_svg(C.header(theme, PROFILE))
    parts.append(f'<svg x="0" y="{y}" width="{W}" height="320" viewBox="0 0 1200 320">{head}</svg>')
    y += 320 + 28

    # 2) metrics strip (880 wide → centre it)
    mx = (W - 880) // 2
    met = strip_svg(C.metrics(theme, PROFILE["metrics"], 880))
    parts.append(f'<svg x="{mx}" y="{y}" width="880" height="112" viewBox="0 0 880 112">{met}</svg>')
    y += 112 + 34

    # 3) about line(s)
    for line in wrap(PROFILE["about"].replace("**", ""), 16, 400, W - 2 * PAD):
        parts.append(f'<text x="{PAD}" y="{y + 14}" font-family="{C.SANS}" font-size="16" fill="{t["text"]}">{C.esc(line)}</text>')
        y += 26
    y += 24

    # 4) tech stack
    title = strip_svg(C.section_title(theme, PROFILE["sections"]["stack"], W - 2 * PAD))
    parts.append(f'<svg x="{PAD}" y="{y}" width="{W - 2 * PAD}" height="56" viewBox="0 0 {W - 2 * PAD} 56">{title}</svg>')
    y += 56 + 14

    per_row = (W - 2 * PAD + GAP) // (TILE + GAP)
    for cat in TECH["categories"]:
        items = [it for it in TECH["tech"] if it["cat"] == cat["id"]]
        if not items:
            continue
        lab = strip_svg(C.category_label(theme, cat["title"], len(items), W - 2 * PAD))
        parts.append(f'<svg x="{PAD}" y="{y}" width="{W - 2 * PAD}" height="34" viewBox="0 0 {W - 2 * PAD} 34">{lab}</svg>')
        y += 40
        for i, it in enumerate(items):
            col = i % per_row
            row = i // per_row
            x = PAD + col * (TILE + GAP)
            parts.append(tile(it["key"], GLYPHS[it["key"]], theme, x, y + row * (TILE + GAP)))
        rows = (len(items) + per_row - 1) // per_row
        y += rows * (TILE + GAP) + 18
    y += 10

    # 5) footer
    parts.append(f'<path d="M{PAD} {y}H{W - PAD}" stroke="{t["cardStroke"]}"/>')
    y += 26
    foot = "Portfolio · LinkedIn · Email · Resume — see the links below"
    parts.append(f'<text x="{W / 2}" y="{y}" text-anchor="middle" font-family="{C.SANS}" font-size="13" fill="{t["muted"]}">{C.esc(foot)}</text>')
    y += 24

    H = y
    return (f'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" '
            f'width="{W}" height="{H}" viewBox="0 0 {W} {H}" role="img" aria-label="Zineb TAHIR — {C.esc(PROFILE["badge"])}">'
            f'<rect width="{W}" height="{H}" fill="{t["card"]}"/>{"".join(parts)}'
            f'<rect x=".5" y=".5" width="{W - 1}" height="{H - 1}" rx="16" fill="none" stroke="{t["cardStroke"]}"/></svg>\n')


def build_readme():
    p, L = PROFILE, PROFILE["links"]
    pic = ('<picture>'
           '<source media="(prefers-color-scheme: dark)" srcset="assets/profile-dark.svg">'
           '<source media="(prefers-color-scheme: light)" srcset="assets/profile-light.svg">'
           '<img alt="Zineb TAHIR — ' + C.esc(p["badge"]) + '" src="assets/profile-dark.svg" width="1000"></picture>')
    about = p["about"]
    md = f"""<!-- Generated by tools/poster.py from tools/profile.json and tools/tech.json. Edit those, then rebuild. -->

<p align="center">
  <a href="{L['portfolio']}">{pic}</a>
</p>

<p align="center">
  <a href="{L['portfolio']}"><b>Portfolio</b></a> ·
  <a href="{L['linkedin']}">LinkedIn</a> ·
  <a href="{L['email']}">Email</a> ·
  <a href="{L['cv']}">Resume (PDF)</a>
</p>

## About me

{about}

My full résumé, projects and certifications are on my **[portfolio]({L['portfolio']})**.

<p align="center"><sub>Poster generated by <a href="tools/">tools/</a> · logos from Simple Icons (CC0) and the AWS Architecture Icons · all trademarks belong to their owners.</sub></p>
"""
    (ROOT / "README.md").write_text(md, encoding="utf-8")


def main():
    out = ROOT / "assets"
    out.mkdir(exist_ok=True)
    for theme in ("dark", "light"):
        (out / f"profile-{theme}.svg").write_text(poster(theme), encoding="utf-8")
        print(f"assets/profile-{theme}.svg  {len((out / f'profile-{theme}.svg').read_bytes())} bytes")
    build_readme()
    print("README.md written")


if __name__ == "__main__":
    sys.exit(main())
